services:
 - type: web
   name: Static Assets
   region: frankfurt
   branch: master
   healthCheckPath: /health
   env: python
   buildCommand: "./build.sh"
   staticPublishPath: ./staticfiles
   startCommand: "gunicorn sapphire_chatbot.wsgi:application"