# Generated by Django 3.2 on 2022-05-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddDressDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddDressFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddDressPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_piece', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddFarewell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='Query in Comma Separated Values: ')),
                ('response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddFoundationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddFragranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragrance_type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddGreeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='Query in Comma Separated Values: ')),
                ('response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddHighlighterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighter_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddScentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scent_type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddShoeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('link', models.TextField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_appv1.addcolor')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_appv1.adddressdesign')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_appv1.adddresspiece')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_appv1.adddressfabric')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/shoes/')),
                ('link', models.TextField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_appv1.addcolor')),
                ('shoe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_appv1.addshoetype')),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/perfumes/')),
                ('link', models.TextField()),
                ('perfume_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_appv1.addfragrancetype')),
                ('scent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_appv1.addscenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Highlighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/highlighters/')),
                ('link', models.TextField()),
                ('highlighter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_appv1.addhighlightertype')),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/bags/')),
                ('link', models.TextField()),
                ('bag_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_appv1.addbagtype')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_appv1.addcolor')),
            ],
        ),
    ]
